perf: increase performance on API retrieval
soumik12345/ml-framework-bot pull request #11
Opened 2024-09-23 14:53 UTC by SauravMaheshkar

* Try to split using `----` as a divider to create separate nodes for each op.

2024-09-25 22:24 UTC, soumik12345 requested changes

2024-09-25 22:24 UTC, soumik12345 commented on ml_frameworks_bot/keras/retriever.py
> +                    if file_path.contains("ops/"):
A better paradigm might be pass this as a parameter in `KerasDocumentationRetreiver.load_documents` (and of course in `KerasDocumentationRetreiver.index_documents`. The paramater could pass a list of file patterns which would use this particular chunking strategy.

2024-10-08 11:17 UTC, soumik12345 approved these changes
LGTM!

2024-10-13 11:10 UTC, SauravMaheshkar commented
Superseded by #13

2024-10-13 11:10 UTC, closed without merging